[package]
name = "sketch_parser"
version = "0.1.0"
authors = ["Mukesh Soni <mukeshsoni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
